#!/bin/sh

SCRIPT=$(readlink -f "$0")
SCRIPT_PATH=$(dirname "$SCRIPT")

ROOT_DIR="$HOME/.bitdust"

if [[ ! -e $ROOT_DIR ]]; then
    mkdir -p $ROOT_DIR
fi

PYTHON_DIR="${ROOT_DIR}/python"
PYTHON_BIN="${PYTHON_DIR}/bin/BitDust-p2p-app"
GIT_BIN="${ROOT_DIR}/git_scm/bin/git"
PIP_BIN="${PYTHON_DIR}/bin/pip3"
SOURCE_UI_DIR="${ROOT_DIR}/ui"
MAIN_PY="${SOURCE_UI_DIR}/src/main.py"

if [[ ! -d "$PYTHON_DIR" ]]; then
    osascript -e "display dialog \"Now the initial setup of the BitDust-p2p-app will be performed.\n\nThe application files will be located in:\n ${ROOT_DIR}\n\nAfter the files are unpacked, the application will launch automatically.\" buttons {\"Continue\"} default button \"Continue\" with icon alias \"Macintosh HD:Applications:BitDust-p2p-app.app:Contents:Resources:bitdust-logo-color.icns\"" && unzip "${SCRIPT_PATH}/../Resources/python.zip" -d "${ROOT_DIR}" && mv "${ROOT_DIR}/.python-portable" "${ROOT_DIR}/python"
fi

if [[ ! -f "$GIT_BIN" ]]; then
    unzip "${SCRIPT_PATH}/../Resources/git_scm.zip" -d "${ROOT_DIR}"
fi

cd "$ROOT_DIR"

if [[ ! -d "$SOURCE_UI_DIR/src" ]]; then
    $GIT_BIN clone git@github.com:bitdust-io/p2p-app.git ui 1>"${ROOT_DIR}/git_scm_out.txt" 2>"${ROOT_DIR}/git_scm_err.txt" || ( \
        osascript -e "display dialog \"Failed to download source code files from GIT repository. Please check your Internet connection and try again.\" buttons {\"Exit\"} default button \"Exit\" with icon alias \"Macintosh HD:Applications:BitDust-p2p-app.app:Contents:Resources:bitdust-logo-color.icns\"" && exit 0 \
    )
else
    cd $SOURCE_UI_DIR && (($GIT_BIN fetch --all 1>"${ROOT_DIR}/git_scm_out.txt" 2>"${ROOT_DIR}/git_scm_err.txt" && $GIT_BIN reset --hard origin/master 1>>"${ROOT_DIR}/git_scm_out.txt" 2>>"${ROOT_DIR}/git_scm_err.txt" ) || ( \
        osascript -e "display dialog \"Failed to update source code files from GIT repository. Please check your Internet connection and try again.\" buttons {\"Exit\"} default button \"Exit\" with icon alias \"Macintosh HD:Applications:BitDust-p2p-app.app:Contents:Resources:bitdust-logo-color.icns\"" && exit 0 \
    )) && cd ..
fi

if [[ ! $(ps axo pid,command | grep "BitDust-p2p-app" | grep "main.py") ]]; then
    cd $SOURCE_UI_DIR && $PYTHON_BIN $MAIN_PY 1>"${ROOT_DIR}/stdout.txt" 2>"${ROOT_DIR}/stderr.txt"
fi
