<MyIDScreen>:

    AppScreenLayout:

        VerticalScrollView:

    	    VerticalWithPaddingLayout:
    	        pos_hint: {'top': 1}
    	        size_hint: 1, None
    	        height: self.minimum_height

    	        MarkupLabel:
    	        	id: my_id_details
    			    size_hint_y: None
    			    text_size: self.width, None
    			    height: self.texture_size[1]
    			    color: app.color_black
    			    text: ''

    			RoundedFlexButton:
    				text: 'key backup'
