<ProcessDeadScreen>:

    VLayout:
        size_hint: 1, 1

        VEmptySpace:
            size_hint_y: 0.5

        HLayout:
            size_hint: 1, .01
    
            HEmptySpace:
                size_hint_x: 0.5

            HFlexMarkupLabel:
                text: '[size=26sp]starting BitDust ...[/size]'

            HEmptySpace:
                size_hint_x: 0.5

        VEmptySpace:
            size_hint_y: 0.5
