<HorizontalLayout>:
	orientation: 'horizontal'
	padding: 0
	spacing: 0


<VerticalLayout>:
	orientation: 'vertical'
	padding: 0
	spacing: 0


<HLayout>:
	orientation: 'horizontal'
	padding: 0
	spacing: 0


<VLayout>:
	orientation: 'vertical'
	padding: 0
	spacing: 0


<HEmptySpace>:
    size_hint_x: 0.5
    size_hint_y: None
    height: 1


<VEmptySpace>:
    size_hint_y: 0.5
    size_hint_x: None
    width: 1


<VerticalScrollView>:
    do_scroll_x: False
