"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

setup(
    app=[
        'launcher.py',
    ],
    data_files=[
        'install.sh',
    ],
    options={
        'py2app': {
            'includes': [
                'virtualenv',
            ],
        },
    },
    setup_requires=[
        'py2app',
    ],
)
